### PR TITLE
Sc 88 implement cafe info card

### PR DESCRIPTION
**Pull request by bettyanhn**
## Describe your changes (point form)

* Add cafe info to cafe info card
* Add image carousel to cafe info page

## Jira Ticket 
88

## Include any Screenshots/Videos if relevant 
no image sorry lol
## Any other reminders reviewers should know? (`npm i`)
run npm i

### CODE REVIEW

**Comment by brandonyhchan** [comment]
Screenshot 2024-09-24 194351
visual bug where the img carousel does not take up teh same width as the cafe info card

**Comment by brandonyhchan** [comment]
Would it be possible on smaller screens to have the cafe info card appear first and then the carousel?

**Comment by brandonyhchan** [comment]
Why does Price work but Noise and Capacity are undefined?

**Comment by bettyanhn** [comment]
oops wrong branch

**Pull request closed without merging**
